# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-14 08:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(db_index=True, max_length=255)),
                ('Quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Type', models.CharField(db_index=True, max_length=5)),
                ('Size', models.CharField(max_length=255)),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
                ('DateTime', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(db_index=True, max_length=255)),
                ('Quantity', models.IntegerField()),
                ('File', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mcs.Files')),
            ],
        ),
        migrations.CreateModel(
            name='Health',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(db_index=True, max_length=255)),
                ('Quantity', models.IntegerField()),
                ('File', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mcs.Files')),
            ],
        ),
        migrations.CreateModel(
            name='SMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Content', models.TextField()),
                ('File', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mcs.Files')),
            ],
        ),
        migrations.CreateModel(
            name='Victims',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(db_index=True, max_length=255)),
                ('Quantity', models.IntegerField()),
                ('File', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mcs.Files')),
            ],
        ),
        migrations.AddField(
            model_name='areas',
            name='File',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mcs.Files'),
        ),
    ]
