# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-14 08:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mcs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(db_index=True, max_length=255)),
                ('Quantity', models.IntegerField()),
                ('File', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mcs.Files')),
            ],
        ),
    ]
