# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcs', '0004_auto_20160216_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='unstructuredtxt',
            name='SentimentPolarity',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
