# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-10 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcs', '0006_files_ttl'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='GroupID',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
