# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-21 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcs', '0008_auto_20160410_1031'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(db_index=True, max_length=255)),
                ('Email', models.CharField(db_index=True, max_length=255)),
                ('Phone', models.IntegerField()),
                ('Designation', models.CharField(db_index=True, max_length=255)),
            ],
        ),
    ]
