# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-07 06:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mcs', '0009_smsregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveSMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Destination', models.CharField(db_index=True, max_length=255)),
                ('Designation', models.CharField(db_index=True, max_length=255)),
                ('DateTime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
