# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-31 13:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mcs', '0011_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummarizedFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('File', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mcs.Files')),
            ],
        ),
    ]
