# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-01 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcs', '0012_summarizedfiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summarizedfiles',
            name='File',
        ),
        migrations.AddField(
            model_name='areas',
            name='lat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='areas',
            name='lon',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='food',
            name='lat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='food',
            name='lon',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='health',
            name='lat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='health',
            name='lon',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='shelter',
            name='lat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='shelter',
            name='lon',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='victims',
            name='lat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='victims',
            name='lon',
            field=models.FloatField(default=0),
        ),
        migrations.DeleteModel(
            name='SummarizedFiles',
        ),
    ]
